### ISSUE TITLE
I have encountered a code problem, can you help me solve it?

### ISSUE THREAD

**Issue by Ma-PC** [Claydon-Wang/OFTTA#1]
I have downloaded the data set as required and placed it in the corresponding folder.When I run it directly, the following error is displayed. Is there an unuploaded .py file?

FileNotFoundError: ./data/ucihar/train/InertialSignals/body_acc_x_train.txt not found.

**Comment by Claydon-Wang** [comment]
Hi there,

You should modify ``data_dir`` in the function ``load_domain_data`` of ``data_process_uci.py``.

Hope the answer can help you.
